service:
  name: myService

# Add the serverless-webpack plugin
plugins:
  - '@hewmen/serverless-plugin-typescript'

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-2

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
